version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: "@types/vscode"
    versions:
    - 1.53.0
    - 1.54.0
    - 1.55.0
