pull_request_rules:
  - name: CI passes and is dev-dependency package from dependabot
    conditions:
      - "#status-success=7"
      - author~=^dependabot(|-preview)\[bot\]$
      - title~=^build\(deps-dev\).*$
      - base=main
    actions:
      merge:
        method: merge
