language: node_js
node_js:
  - "lts/*"

stages:
  - name: build
  - name: release
    if: tag IS present

jobs:
  include:
    - stage: build
      script:
        # test that the extension builds correctly
        - yarn build
    - stage: release
      script:
        # fail fast
        - set -e
        # configure git so that we can commit and push the new version
        - git config --global user.email "metals@scalameta.org"
        - git config --global user.name "Metals CI"
        # drop the v prefix in vX.Y.Z
        - NEW_VERSION=${TRAVIS_TAG#"v"}
        # checkout to a temporary branch to allow commits
        - git checkout -b travis-temp
        # change the version in package.json
        - yarn version --no-git-tag-version --new-version $NEW_VERSION
        - npx github-changes -o scalameta -r metals-vscode --no-merges -t "VSCode Extension Changelog" -k $GITHUB_TOKEN
        - sed -i '1i Check out the Metals release notes at [https://scalameta.org/metals/blog/](https://scalameta.org/metals/blog/)\n' CHANGELOG.md
        - git commit -am "$TRAVIS_TAG"
        # push the changes to package.json
        - git push "https://${GITHUB_TOKEN}@github.com/$TRAVIS_REPO_SLUG" HEAD:master
        # publish the extension to the Marketplace
        - yarn vscode:publish -p $VS_MARKETPLACE_TOKEN

cache: yarn
